services:
  chainlit-app:
    build:
      context: ../
    container_name: chainlit_container
    ports:
      - "8000:8000"
    volumes:
      - ../:/app        
    working_dir: /app  
    restart: unless-stopped
    networks:
      - gwen-chatbot
    depends_on:
      - redis
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
